# Generated by Django 2.2.8 on 2020-02-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woocustomer',
            name='customer_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wooorder',
            name='order_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wooorderitem',
            name='orderitem_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='woovariant',
            name='variant_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
