# Generated by Django 2.2.8 on 2020-02-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200212_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='woocustomer',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='woocustomer',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='woocustomer',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='woocustomer',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
