# Generated by Django 2.2.8 on 2020-02-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200211_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wooproduct',
            name='price',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wooproduct',
            name='regular_price',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wooproduct',
            name='sale_price',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wooproduct',
            name='total_sales',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
