# Generated by Django 2.2.8 on 2020-02-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200213_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='wooorder',
            name='customer_ip_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wooorder',
            name='customer_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
