# Generated by Django 2.2.8 on 2020-02-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200214_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='wooorderitem',
            name='id_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
