# Generated by Django 2.2.8 on 2020-02-19 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200218_1835'),
        ('core', '0008_auto_20200219_0024'),
    ]

    operations = [
    ]
