# Generated by Django 2.2.8 on 2020-02-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200219_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('fortnox', 'Fortnox'), ('visma', 'Visma')], default='fortnox', max_length=128),
        ),
    ]
