# Generated by Django 2.2.8 on 2020-03-02 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200220_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='fortnoxSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('sales_account_25', models.IntegerField(blank=True, null=True, unique=True)),
                ('sales_account_12', models.IntegerField(blank=True, null=True, unique=True)),
                ('sales_account_6', models.IntegerField(blank=True, null=True, unique=True)),
                ('seller_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
