# Generated by Django 2.2.8 on 2020-03-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_fortnoxsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortnoxsettings',
            name='freight_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
