# Generated by Django 2.2.8 on 2020-03-03 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200303_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortnoxsettings',
            name='seller_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
