# Generated by Django 2.2.8 on 2020-03-03 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200303_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fortnoxsettings',
            name='id',
        ),
        migrations.AlterField(
            model_name='fortnoxsettings',
            name='seller_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
