# Generated by Django 2.2.8 on 2020-03-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200303_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('fortnox', 'Fortnox'), ('visma', 'Visma')], max_length=128, null=True),
        ),
    ]
